general:
  data_path: data/
  model_path: models/
  result_path: results_localtesting/
  log_path: logs/
  random_state: 345
  random_seed: 345
  logging_level: INFO
  n_jobs: 4
  save_every_n_iterations: 10

experiments_setup:
  robust_cf_method: "betarob" # robx or betarob
  ex_types:
    - "Architecture"
    - "Seed"
    # - "Bootstrap-Architecture"
    # - "Seed-Bootstrap"
    # - "Seed-Architecture"
    # - "Seed-Bootstrap-Architecture"
    # - "Bootstrap"
  perform_generalizations: False
  datasets:
    - "fico"
    # - "wine_quality"
    # - "breast_cancer"
  beta_confidences:
    # - 0.8
    # - 0.9
    - 0.95
  delta_robustnesses:
    # - 0.5
    # - 0.6
    # - 0.7
    # - 0.8
    - 0.9
  x_test_size: 2
  m_count_per_experiment: 2
  cross_validation_folds: 3
  base_counterfactual_method: "gs" # - "dice"
  metrics_to_calculate:
    - "validity"
    - "proximityL1"
    - "proximityL2"
    - "plausibility"
    - "dpow"
  model_type_to_use:  "neural_network" # - "random_forest"
  

model_hyperparameters:
  neural_network:
    model_hyperparameters_pool:
      hidden_layers:
        - 2
        - 3
        - 4
      neurons_per_layer:
        - 16
        - 24
        - 32
        - 48
        - 64
        - 80
        - 96
        - 112
        - 128
        - 144
        - 192
        - 224
        - 256
      activation:
        - "relu"
        - "tanh"
      optimizer:
        - "adam"
    model_fixed_hyperparameters:
      hidden_layers: 3
      neurons_per_layer: 128
      activation: "relu"
      optimizer: "adam"
    model_fixed_seed: 42
    model_base_hyperparameters:
      loss: "BCELoss"
      early_stopping: True
      lr: 0.001
      epochs: 100
      batch_size: 128
      verbose: True
      dropout: 0.4
      classification_threshold: 0.5  

  random_forest:
    model_hyperparameters_pool:
      n_estimators:
        - 10
        - 20
        - 30
        - 40
        - 50
        - 60
        - 70
        - 80
        - 90
        - 100
      max_depth:
        - 4
        - 8
        - 10
        - 12
        - 14
        - 16
        - 18
        - 20
        - 24
      min_samples_split:
        - 2
        - 3
        - 4
        - 5
      min_samples_leaf:
        - 1
        - 2
        - 3
        - 4
        - 5
    model_fixed_hyperparameters:
      n_estimators: 50
      max_depth: 10
      min_samples_split: 2
      min_samples_leaf: 1
    model_fixed_seed: 42

beta_rob:
  k_mlps_in_B: 
    - 32
  growingSpheresHparams:
    max_iter: 100
    n_search_samples: 100
    p_norm: 2
    step: 0.1
    target_proba: 0.5

robx:
  taus:
    - 0.4 
    - 0.5
    - 0.6
    - 0.7
    - 0.8
  variances: 
    - 0.01
  N: 1000
