general:
  data_path: data/
  model_path: models/
  result_path: results/
  log_path: logs/
  random_state: 3456
  logging_level: INFO

mlp:
  hidden_layer_sizes: [100, 100]
  activation: relu
  solver: adam
  learning_rate_init: 0.01
  max_iter: 1000
  verbose: true
  early_stopping: true
  random_state: 3456

rf:
  n_estimators: 100
  max_depth: 10
  random_state: 3456
  
robXHparams:
  tau: 0.7
  variance: 0.01
  N: 1000

experiment:
  classification_threshold: 0.5
