general:
  data_path: data/
  model_path: models/
  result_path: reuslts_ex2/
  log_path: logs/
  random_state: 345
  random_seed: 345
  logging_level: INFO
  n_jobs: 4

experiments_setup:
  ex_types:
    - "Bootstrap"
    - "Architecture"
    - "Bootstrap-Architecture"
    - "Seed"
    - "Seed-Bootstrap"
    - "Seed-Architecture"
    - "Seed-Bootstrap-Architecture"
  datasets:
    - "fico"
    - "breast_cancer"
    - "wine_quality"
  beta_confidences:
    - 0.8
    - 0.9
    - 0.95
    - 0.99
  delta_robustnesses:
    - 0.5
    - 0.6
    - 0.7
    - 0.8
    - 0.9
    - 0.95
    - 0.99
  x_test_size: 100
  m_count_per_experiment: 15
  cross_validation_folds: 5
  base_counterfactual_method: 
    - "GrowingSpheres"
    - "Dice"
  metrics_to_calculate:
    - "validity"
    - "proximityL1"
    - "proximityL2"
    - "plausibility"
    - "dpow"
  model_type_to_use: 
    - "neural_network"
    - "random_forest"
  

model_hyperparameters:
  neural_network:
    model_hyperparameters_pool:
      hidden_layers:
        - 2
        - 3
        - 4
      neurons_per_layer:
        - 64
        - 96
        - 128
        - 192
        - 256
      activation:
        - "relu"
      optimizer:
        - "adam"
        - "sgd"
    model_fixed_hyperparameters:
      hidden_layers: 3
      neurons_per_layer: 128
      activation: "relu"
      optimizer: "adam"
    model_fixed_seed: 42
    model_base_hyperparameters:
      loss: "BCELoss"
      early_stopping: True
      lr: 0.001
      epochs: 100
      batch_size: 128
      verbose: True
      dropout: 0.2
      classification_threshold: 0.5

      

  random_forest:
    model_hyperparameters_pool:
      n_estimators:
        - 100
        - 200
      max_depth:
        - 10
        - 20
    model_fixed_hyperparameters:
      n_estimators: 100
      max_depth: 10
    model_fixed_seed: 42

beta_rob:
  k_mlps_in_B: 30
  growingSpheresHparams:
    max_iter: 100
    n_search_samples: 100
    p_norm: 2
    step: 0.05
    target_proba: 0.5
