beta_rob:
  growingSpheresHparams:
    max_iter: 100
    n_search_samples: 100
    p_norm: 2
    step: 0.1
    target_proba: 0.5
  k_mlps_in_B:
  - 32
experiments_setup:
  base_counterfactual_method: gs
  beta_confidences:
  - 0.95
  cross_validation_folds: 5
  datasets:
  - fico
  - breast_cancer
  - wine_quality
  delta_robustnesses:
  - 0.5
  - 0.6
  - 0.7
  - 0.8
  - 0.9
  ex_types:
  - Bootstrap-Architecture
  - Seed-Bootstrap
  - Seed-Architecture
  - Seed-Bootstrap-Architecture
  m_count_per_experiment: 30
  metrics_to_calculate:
  - validity
  - proximityL1
  - proximityL2
  - plausibility
  - dpow
  model_type_to_use: neural_network
  perform_generalizations: false
  x_test_size: 30
general:
  data_path: data/
  log_path: logs/
  logging_level: INFO
  model_path: models/
  n_jobs: 4
  random_seed: 345
  random_state: 345
  result_path: reuslts_ex2/
  save_every_n_iterations: 100
model_hyperparameters:
  neural_network:
    model_base_hyperparameters:
      batch_size: 128
      classification_threshold: 0.5
      dropout: 0.4
      early_stopping: true
      epochs: 100
      loss: BCELoss
      lr: 0.001
      verbose: true
    model_fixed_hyperparameters:
      activation: relu
      hidden_layers: 3
      neurons_per_layer: 128
      optimizer: adam
    model_fixed_seed: 42
    model_hyperparameters_pool:
      activation:
      - relu
      - tanh
      hidden_layers:
      - 2
      - 3
      - 4
      neurons_per_layer:
      - 16
      - 24
      - 32
      - 48
      - 64
      - 80
      - 96
      - 112
      - 128
      - 144
      - 192
      - 224
      - 256
      optimizer:
      - adam
  random_forest:
    model_fixed_hyperparameters:
      max_depth: 10
      n_estimators: 100
    model_fixed_seed: 42
    model_hyperparameters_pool:
      max_depth:
      - 8
      - 10
      - 12
      - 14
      - 16
      - 18
      - 20
      n_estimators:
      - 25
      - 50
      - 75
      - 100
      - 125
      - 150
      - 175
      - 200
