general:
  data_path: data/
  model_path: /home/inf148179/robust-cf/models/
  result_path: /home/inf148179/robust-cf/aaai_experiments/results_aaai/robx/dice/wine_qualityS/
  log_path: /home/inf148179/robust-cf/aaai_experiments/logs_aaai/
  random_state: 345
  random_seed: 345
  logging_level: INFO
  n_jobs: 4
  save_every_n_iterations: 100

experiments_setup:
  robust_cf_method: "robx" # robx or betarob
  ex_types:
    # - "Architecture"
    # - "Bootstrap"
    - "Seed"
  perform_generalizations: False
  datasets:
    - "wine_quality"
  beta_confidences:
    - 0.95
  delta_robustnesses:
    - 0.7
    - 0.8
    - 0.9
  x_test_size: 30
  m_count_per_experiment: 30
  cross_validation_folds: 3
  base_counterfactual_method: "dice" # - "dice"
  metrics_to_calculate:
    - "validity"
    - "proximityL1"
    - "proximityL2"
    - "plausibility"
    - "dpow"
  model_type_to_use:  "neural_network" # - "random_forest"
  just_base_cf: False
  

model_hyperparameters:
  neural_network:
    model_hyperparameters_pool:
      hidden_layers:
        lower: 3
        upper: 5
      neurons_per_layer:
        lower: 64
        upper: 256
      activation:
        - "relu"
      optimizer:
        - "adam"
    model_fixed_hyperparameters:
      hidden_layers: 3
      neurons_per_layer: 128
      activation: "relu"
      optimizer: "adam"
    model_fixed_seed: 42
    model_base_hyperparameters:
      loss: "BCELoss"
      early_stopping: True
      lr: 0.001
      epochs: 100
      batch_size: 128
      verbose: True
      dropout: 0.4
      classification_threshold: 0.5  

  random_forest:
    model_hyperparameters_pool:
      n_estimators:
        - 25
        - 50
        - 75
        - 100
        - 125
        - 150
        - 175
        - 200
      max_depth:
        - 8
        - 10
        - 12
        - 14
        - 16
        - 18
        - 20
    model_fixed_hyperparameters:
      n_estimators: 100
      max_depth: 10
    model_fixed_seed: 42

beta_rob:
  k_mlps_in_B: 
    - 32
  growingSpheresHparams:
    max_iter: 100
    n_search_samples: 100
    p_norm: 2
    step: 0.1
    target_proba: 0.5

robx:
  taus:
    - 0.7
  variances: 
    - 0.01
  N: 1000