general:
  data_path: data/
  model_path: /home/inf148179/robust-cf/aaai_experiments/models/
  result_path: /home/inf148179/robust-cf/aaai_experiments/results_aaai/base/dice/
  log_path: /home/inf148179/robust-cf/aaai_experiments/logs_aaai/base/
  random_state: 123
  random_seed: 123
  logging_level: INFO
  n_jobs: 4
  save_every_n_iterations: 100

experiments_setup:
  robust_cf_method: "betarob" # robx or betarob
  ex_types:
    - "Architecture"
    - "Bootstrap"
    - "Seed"
  perform_generalizations: False
  datasets:
    - "diabetes"
    - "fico"
    - "breast_cancer"
    - "wine_quality"
  beta_confidences:
    - 0.95
  delta_robustnesses:
    - 0.7
    - 0.8
    - 0.9
  x_test_size: 30
  m_count_per_experiment: 30
  cross_validation_folds: 3
  base_counterfactual_method: "dice" # - "dice"
  metrics_to_calculate:
    - "validity"
    - "proximityL1"
    - "proximityL2"
    - "plausibility"
    - "dpow"
  model_type_to_use:  "neural_network" # - "random_forest"
  just_base_cf: True
  

model_hyperparameters:
  neural_network:
    model_hyperparameters_pool:
      hidden_layers:
        lower: 3
        upper: 5
      neurons_per_layer:
        lower: 64
        upper: 256
      activation:
        - "relu"
      optimizer:
        - "adam"
    model_fixed_hyperparameters:
      hidden_layers: 3
      neurons_per_layer: 128
      activation: "relu"
      optimizer: "adam"
    model_fixed_seed: 42
    model_base_hyperparameters:
      loss: "BCELoss"
      early_stopping: True
      lr: 0.001
      epochs: 100
      batch_size: 128
      verbose: True
      dropout: 0.4
      classification_threshold: 0.5  

  random_forest:
    model_hyperparameters_pool:
      n_estimators:
        - 25
        - 50
        - 75
        - 100
        - 125
        - 150
        - 175
        - 200
      max_depth:
        - 8
        - 10
        - 12
        - 14
        - 16
        - 18
        - 20
    model_fixed_hyperparameters:
      n_estimators: 100
      max_depth: 10
    model_fixed_seed: 42

beta_rob:
  k_mlps_in_B: 
    - 32
  growingSpheresHparams:
    max_iter: 100
    n_search_samples: 100
    p_norm: 2
    step: 0.1
    target_proba: 0.5

gs:
  max_iter: 100
  n_search_samples: 100
  p_norm: 2
  step: 0.1
  target_proba: 0.5

robx:
  taus:
    - 0.4 
    - 0.5
    - 0.6
    - 0.7
    - 0.8
  variances: 
    - 0.01
  N: 1000

roar:
  delta_max: [0.01, 0.05, 0.1]
  lr: [0.01, 0.05, 0.1]
  norm: [1, 2]

rbr: 
  ec:
    num_samples: 100
    max_distance: 1.0
    rbr_params: 
        delta_plus: [0.0, 0.1, 0.2]
        sigma: [0.5, 1.0, 1.5]
        epsilon_op: 0.0
        epsilon_pe: 0.0
  perturb_radius:
      synthesis: [0.1, 0.2, 0.3]
  device: "cpu"

face:
  mode: ['knn', 'epsilon']
  fraction: [0.1, 0.3, 0.5]

dice: 
  proximity_weight: [0.05, 0.1, 0.2]
  diversity_weight: [0.05, 0.1, 0.2]
  sparsity_weight: [0.05, 0.1, 0.2]
