defaults:
  # - override hydra/launcher: joblib
  - override hydra/launcher: submitit_slurm

hydra:
  launcher:
    # JOBLIB max jobs
    # n_jobs: 10

    # SLURM
    cpus_per_task: 1
    mem_per_cpu: 6G
    timeout_min: 10080
    partition: obl


general:
  data_path: data/
  model_path: kdd/models/
  result_path: kdd/results/params/
  log_path: kdd/logs/
  save_format: feather
  random_state: 345
  random_seed: 345
  logging_level: INFO
  n_jobs: 1

experiments_setup:
  pretrain: True
  n_pretrain: 50
  base_explainers:
    - "gs"
  e2e_explainers:
  posthoc_explainers:
    - "betarob"
  ex_types:
    - "Architecture"
  perform_generalizations: False
  datasets:
    - "breast_cancer"
  x_test_size: 30
  m2_count: 30
  cross_validation_folds: 3
  metrics_to_calculate:
    - "validity"
    - "proximityL1"
    - "proximityL2"
    - "plausibility"
    - "dpow"
  classifiers:
    - "neural_network"
  pretrain_N: 100
  save_every: 1000
  
model_hyperparameters:
  neural_network:
    model_hyperparameters_pool:
      hidden_layers:
        lower: 3
        upper: 5
      neurons_per_layer:
        lower: 32
        upper: 256
      activation:
        - "relu"
      optimizer:
        - "adam"
    model_fixed_hyperparameters:
      hidden_layers: 3
      neurons_per_layer: 128
      activation: "relu"
      optimizer: "adam"
    model_fixed_seed: 42
    model_base_hyperparameters:
      loss: "BCELoss"
      early_stopping: True
      lr: 0.001
      epochs: 100
      batch_size: 128
      verbose: True
      dropout: 0.4
      classification_threshold: 0.5  

  decision_tree:
    model_hyperparameters_pool:
      max_depth:
        lower: 5
        upper: 10
      min_samples_split:
        lower: 2
        upper: 5
      min_samples_leaf:
        lower: 1
        upper: 4
      criterion:
        - "gini"
        - "entropy"
        - "log_loss"
      max_features:
        - "sqrt"
        - "log2"
    model_fixed_hyperparameters:
      max_depth: 8
      min_samples_split: 2
      min_samples_leaf: 1
      criterion: "gini"
      max_features: "sqrt"
    model_fixed_seed: 42
    model_base_hyperparameters:
      criterion: "gini"
      verbose: 0
      n_jobs: 1
      seed: 42
      classification_threshold: 0.5

  lightgbm:
    model_hyperparameters_pool:
      num_leaves:
        lower: 10
        upper: 20
      n_estimators:
        lower: 15
        upper: 40
      min_child_samples:
        lower: 10
        upper: 20
      subsample:
        lower: 0.5
        upper: 1
        resolution: 10
    model_base_hyperparameters:
      objective: "binary"
      verbose: -1
      seed: 42
      classification_threshold: 0.5
      n_jobs: 4
    model_fixed_hyperparameters:
      num_leaves: 15
      n_estimators: 30
      min_child_samples: 20
      subsample: 0.8
    model_fixed_seed: 42


  logistic_regression:
    model_hyperparameters_pool:
      C:
        lower: 0.1
        upper: 1.0
        resolution: 10
      penalty:
        - "l2"
        - null
      max_iter:
        lower: 50
        upper: 200
        resolution: 10
      solver:
        - "lbfgs"
        - "newton-cg"
        - "sag"
    model_base_hyperparameters:
      verbose: 0
      n_jobs: 1
      classification_threshold: 0.5
      seed: 42
    model_fixed_hyperparameters:
      C: 1
      penalty: "l2"
      max_iter: 100
      solver: "lbfgs"
    model_fixed_seed: 42
      
betarob:
  pool_hps:
    k: 
      - 8
      - 12
      - 16
      - 20
      - 24
      - 28
      - 32
      - 36
      - 40
      - 44
      - 48
      - 52
    beta:
      - 0.6
      - 0.7
      - 0.8
      - 0.9
    delta:
      - 0.6
      - 0.7
      - 0.8
      - 0.9
  fixed_hps:
    gs:
      max_iter: 100
      n_search_samples: 100
      p_norm: 2
      step: 0.1
      target_proba: 0.5

gs:
  max_iter: 100
  n_search_samples: 100
  p_norm: 2
  step: 0.1
  target_proba: 0.5

robx:
  pool_hps:
    tau: 
      - 0.5
    variance: 
      - 0.1
      - 0.01
  fixed_hps:
    N: 1000

roar:
  delta_max: [0.01, 0.05, 0.1]
  lr: [0.01, 0.05, 0.1]
  norm: [1, 2]

rbr: 
  ec:
    num_samples: 100
    max_distance: 1.0
    rbr_params: 
        delta_plus: [0.0, 0.1, 0.2]
        sigma: [0.5, 1.0, 1.5]
        epsilon_op: 0.0
        epsilon_pe: 0.0
  perturb_radius:
      synthesis: [0.1, 0.2, 0.3]
  device: "cpu"

face:
  mode: ['knn', 'epsilon']
  fraction: [0.1, 0.3, 0.5]

dice: 
  proximity_weight: [0.05, 0.1, 0.2]
  diversity_weight: [0.05, 0.1, 0.2]
  sparsity_weight: [0.05, 0.1, 0.2]
