general:
  data_path: data/
  model_path: models/
  result_path: results_lgbm/gs_wine/
  log_path: logs_lgbm/
  random_state: 123
  random_seed: 123
  logging_level: INFO
  n_jobs: 4
  save_every_n_iterations: 100

experiments_setup:
  robust_cf_method: "betarob" # robx or betarob
  ex_types:
    - "Architecture"
    - "Bootstrap"
    - "Seed"
  perform_generalizations: False
  datasets:
    - "wine_quality"
  beta_confidences:
    - 0.95
  delta_robustnesses:
    - 0.8
    - 0.9
  x_test_size: 50
  m_count_per_experiment: 50
  cross_validation_folds: 3
  base_counterfactual_method: "gs" # - "dice"
  metrics_to_calculate:
    - "validity"
    - "proximityL1"
    - "proximityL2"
    - "plausibility"
    - "dpow"
  model_type_to_use:  "lightgbm" # - "random_forest"
  

model_hyperparameters:
  lightgbm:
    model_hyperparameters_pool:
      num_leaves:
        lower: 10
        upper: 20
      n_estimators:
        lower: 15
        upper: 40
      min_child_samples:
        lower: 10
        upper: 20
      subsample:
        lower: 0.5
        upper: 1
        freq: 0.1
    model_base_hyperparameters:
      objective: "binary"
      verbose: -1
      seed: 42
      classification_threshold: 0.5
      n_jobs: 4
    model_fixed_hyperparameters:
      num_leaves: 15
      n_estimators: 30
      min_child_samples: 20
      subsample: 0.8
    model_fixed_seed: 42
  neural_network:
    model_hyperparameters_pool:
      hidden_layers:
        lower: 3
        upper: 5
      neurons_per_layer:
        lower: 64
        upper: 256
      activation:
        - "relu"
      optimizer:
        - "adam"
    model_fixed_hyperparameters:
      hidden_layers: 3
      neurons_per_layer: 128
      activation: "relu"
      optimizer: "adam"
    model_fixed_seed: 42
    model_base_hyperparameters:
      loss: "BCELoss"
      early_stopping: True
      lr: 0.001
      epochs: 100
      batch_size: 128
      verbose: True
      dropout: 0.4
      classification_threshold: 0.5  

  random_forest:
    model_hyperparameters_pool:
      n_estimators:
        - 25
        - 50
        - 75
        - 100
        - 125
        - 150
        - 175
        - 200
      max_depth:
        - 8
        - 10
        - 12
        - 14
        - 16
        - 18
        - 20
    model_fixed_hyperparameters:
      n_estimators: 100
      max_depth: 10
    model_fixed_seed: 42

beta_rob:
  k_mlps_in_B: 
    - 32
  growingSpheresHparams:
    max_iter: 100
    n_search_samples: 100
    p_norm: 2
    step: 0.1
    target_proba: 0.5

robx:
  taus:
    - 0.7
  variances: 
    - 0.01
  N: 1000